In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('CO2 Emissions_Canada.csv')
df.head()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [3]:
for column in df.select_dtypes(include='object').columns:
    print(column, ':', df[column].nunique())

Make : 42
Model : 2053
Vehicle Class : 16
Transmission : 27
Fuel Type : 5

In [4]:
df.rename(columns={'Make' : 'Vehicle Brand'}, inplace=True)
df.drop('Model', axis=1, inplace=True)

In [5]:
df.head()

,Vehicle Brand,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [6]:
df['Transmission Type'] = df['Transmission'].apply(lambda x: ''.join(filter(str.isalpha, x)))
df['Number of Gears'] = df['Transmission'].apply(lambda x: int(''.join(filter(str.isdigit, x))) if any(char.isdigit() for char in x) else np.nan)

df.drop('Transmission', axis=1, inplace=True)
df.head()

,Vehicle Brand,Vehicle Class,Engine Size(L),Cylinders,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),Transmission Type,Number of Gears
0,ACURA,COMPACT,2.0,4,Z,9.9,6.7,8.5,33,196,AS,5.0
1,ACURA,COMPACT,2.4,4,Z,11.2,7.7,9.6,29,221,M,6.0
2,ACURA,COMPACT,1.5,4,Z,6.0,5.8,5.9,48,136,AV,7.0
3,ACURA,SUV - SMALL,3.5,6,Z,12.7,9.1,11.1,25,255,AS,6.0
4,ACURA,SUV - SMALL,3.5,6,Z,12.1,8.7,10.6,27,244,AS,6.0

In [7]:
print(sorted(list(df['Fuel Type'].unique())))

['D', 'E', 'N', 'X', 'Z']

In [43]:
df.dtypes

Vehicle Brand                        object
Vehicle Class                        object
Engine Size(L)                      float64
Cylinders                             int64
Fuel Type                            object
Fuel Consumption City (L/100 km)    float64
Fuel Consumption Hwy (L/100 km)     float64
Fuel Consumption Comb (L/100 km)    float64
Fuel Consumption Comb (mpg)           int64
CO2 Emissions(g/km)                   int64
Transmission Type                    object
Number of Gears                     float64
dtype: object

In [44]:
df.isnull().sum()

Vehicle Brand                         0
Vehicle Class                         0
Engine Size(L)                        0
Cylinders                             0
Fuel Type                             0
Fuel Consumption City (L/100 km)      0
Fuel Consumption Hwy (L/100 km)       0
Fuel Consumption Comb (L/100 km)      0
Fuel Consumption Comb (mpg)           0
CO2 Emissions(g/km)                   0
Transmission Type                     0
Number of Gears                     295
dtype: int64

In [ ]:
mode_value = df['Number of Gears'].mode()[0]
df['Number of Gears'].fillna(mode_value, inplace=True)

In [53]:
df.isnull().sum()

Vehicle Brand                       0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
Transmission Type                   0
Number of Gears                     0
dtype: int64

In [54]:
df['Number of Gears'] = df['Number of Gears'].astype('int64')
df.head()

,Vehicle Brand,Vehicle Class,Engine Size(L),Cylinders,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),Transmission Type,Number of Gears
0,ACURA,COMPACT,2.0,4,Z,9.9,6.7,8.5,33,196,AS,5
1,ACURA,COMPACT,2.4,4,Z,11.2,7.7,9.6,29,221,M,6
2,ACURA,COMPACT,1.5,4,Z,6.0,5.8,5.9,48,136,AV,7
3,ACURA,SUV - SMALL,3.5,6,Z,12.7,9.1,11.1,25,255,AS,6
4,ACURA,SUV - SMALL,3.5,6,Z,12.1,8.7,10.6,27,244,AS,6

In [55]:
df.dtypes

Vehicle Brand                        object
Vehicle Class                        object
Engine Size(L)                      float64
Cylinders                             int64
Fuel Type                            object
Fuel Consumption City (L/100 km)    float64
Fuel Consumption Hwy (L/100 km)     float64
Fuel Consumption Comb (L/100 km)    float64
Fuel Consumption Comb (mpg)           int64
CO2 Emissions(g/km)                   int64
Transmission Type                    object
Number of Gears                       int64
dtype: object